
apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: my-app-test
  namespace: default
spec:
  parallelism: 1
  script:
    configMap:
      name: k6-test-script
      file: k6-test.js
  arguments: --out influxdb=http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090/k6
