apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: recreate-pipeline
spec:
  params:
    - name: manifest
      description: The Kubernetes manifest to apply
      type: string
    - name: deployment-name
      description: The name of the deployment to update
      type: string
    - name: image
      description: The new image to use
      type: string
    - name: container-name
      description: The name of the container to update
      type: string
  tasks:
    - name: apply-deployment
      taskRef:
        name: apply-manifests
      params:
        - name: manifest
          value: "$(params.manifest)"
    - name: update-deployment
      runAfter:
        - apply-deployment
      taskRef:
        name: update-image
      params:
        - name: deployment-name
          value: "$(params.deployment-name)"
        - name: image
          value: "$(params.image)"
        - name: container-name
          value: "$(params.container-name)"
