apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: recreate-pipelinerun
spec:
  pipelineRef:
    name: recreate-pipeline
  params:
    - name: manifest
      value: |
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: my-app
        spec:
          replicas: 3
          strategy:
            type: Recreate
          selector:
            matchLabels:
              app: my-app
          template:
            metadata:
              labels:
                app: my-app
            spec:
              containers:
              - name: my-app
                image: nginx:1.16.1
                ports:
                - containerPort: 80
        ---
        apiVersion: v1
        kind: Service
        metadata:
          name: my-app
        spec:
          selector:
            app: my-app
          ports:
            - protocol: TCP
              port: 80
              targetPort: 80
    - name: deployment-name
      value: "my-app"
    - name: image
      value: "nginx:1.17.1"
    - name: container-name
      value: "my-app"
